

%test default architecture creation
testDefault = MarsArchitecture.DEFAULT;
testDRA5 = MarsArchitecture.DRA5;

test2choice = MarsArchitecture.Enumerate({Propulsion.NTR,Propulsion.LH2,Propulsion.SEP},{FoodSource.EARTH_ONLY,FoodSource.EARTH_MARS_50_SPLIT,FoodSource.MARS_ONLY});

test3choice = MarsArchitecture.Enumerate( ... 
    {Propulsion.NTR,Propulsion.LH2}, ...
    {Site.HOLDEN,Site.GALE}, ...
    {FoodSource.EARTH_ONLY,FoodSource.EARTH_MARS_50_SPLIT,FoodSource.MARS_ONLY});

test2fuel = MarsArchitecture.Enumerate( ...
    {[TransitFuel.EARTH_O2,TransitFuel.LUNAR_LH2],[TransitFuel.LUNAR_O2, TransitFuel.LUNAR_LH2]}, ...
    {[ReturnFuel.EARTH_O2, ReturnFuel.EARTH_LH2],[ReturnFuel.MARS_O2,ReturnFuel.MARS_LH2]});
    
stageLocTest = MarsArchitecture.Enumerate({Location.EARTH,Location.LEO,Location.EML1});

startTime = datetime;
        %{CrewTrajectory.HOHMANN}
% EverythingUnderTheSun = MarsArchitecture.Enumerate( ...
%         {Propulsion.LH2,Propulsion.NTR,Propulsion.SEP,Propulsion.CH4}, ...
%         {CargoTrajectory.HOHMANN,CargoTrajectory.ELLIPTICAL}, ...
%         {TransitFuel.EARTH_LH2,[TransitFuel.EARTH_LH2,TransitFuel.LUNAR_O2],[TransitFuel.LUNAR_LH2,TransitFuel.LUNAR_O2]}, ...
%         {Crew.MIN_CREW,Crew.DEFAULT_TRANSIT,Crew.DRA_CREW}, ...
%         {HabitatShielding.DEDICATED,HabitatShielding.H2O_INSULATION}, ...
%         {ArrivalEntry.AEROCAPTURE,ArrivalEntry.AEROBRAKE,ArrivalEntry.PROPULSIVE,ArrivalEntry.DIRECT}, ...
%         {ArrivalDescent.PROPULSIVE,ArrivalDescent.CHUTE,ArrivalDescent.SHOCK_ABSORBTION}, ...
%         {Site.HOLDEN,Site.GALE}, ...
%         {FoodSource.EARTH_ONLY,FoodSource.EARTH_MARS_50_SPLIT,FoodSource.MARS_ONLY}, ...
%         {SurfaceShielding.DEDICATED,SurfaceShielding.H2O_INSULATION,SurfaceShielding.REGOLITH,SurfaceShielding.BURIED}, ...
%         {PowerSource.SOLAR,PowerSource.NUCLEAR,[PowerSource.NUCLEAR, PowerSource.SOLAR, PowerSource.RTG]});%, ...
%         %{StructureType.FIXED_SHELL,StructureType.INFLATABLE,{StructureType.FIXED_SHELL, 0.500; StructureType.INFLATABLE, 0.500}}, ...
%         %{ReturnFuel.EARTH_LH2,[ReturnFuel.EARTH_LH2, ReturnFuel.MARS_O2],[ReturnFuel.MARS_LH2,ReturnFuel.MARS_O2]}, ...
%         %{ReturnEntry.AEROCAPTURE,ReturnEntry.AEROBRAKE,ReturnEntry.PROPULSIVE,ReturnEntry.DIRECT}, ...
%         %{ReturnDescent.PROPULSIVE,ReturnDescent.CHUTE,ReturnDescent.SHOCK_ABSORBTION});
%         
endTime = datetime;
endTime-startTime;